version: 2

models:
  - name: stg_yellow_tripdata__cleaned_sources
    columns:
      - name: trip_duration_min
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: VendorID
        tests:
          - unique
          - not_null
      - name: RatecodeID
        tests:
          - accepted_values:
              values: [ 1, 2, 3, 4, 5, 6]
      - name: store_and_fwd_flag
        tests:
          - accepted_values:
              values: ['Y', 'N']
