version: 2

models:
  - name: stg_yellow_tripdata__cleaned_sources
    columns:
      - name: VendorID
        tests:
          - not_null
      - name: pickup_timestamp
        tests:
          - not_null
      - name: dropoff_timestamp
        tests:
          - not_null
      - name: trip_duration_min
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
